### ISSUE TITLE
add to all fields a json tag

### ISSUE THREAD

**Issue by patsys** [ContainerSSH/ContainerSSH#116] opened 2021-02-28 20:46 UTC
## Please describe what you need help with
this is not a Support request and not a other request, just a nice to have.
I play the first time with the operator-sdk this need by all fields a json tag. By fields not Serializable schould use `json:"-"`
...

## Have you read the readme in its entirety?
yes
...

## What have you tried to resolve this problem?
I have begin with add in line https://github.com/ContainerSSH/http/blob/main/client.go#
```caCertPool *x509.CertPool `json:"-"` ```

and when the json tag is by all fields correct I get it work. 
...

**Comment by janoszen** [comment] 2021-03-01 06:51
Hello @patsys thank you very much, we will add the tags for all config fields for the next preview release.

**Comment by janoszen** [comment] 2021-03-13 10:52
@patsys did you have a chance to test if the tags are now working as intended? Thanks!

**Comment by patsys** [comment] 2021-03-13 11:40
@janoszen I have test it and get this errors:

`/Users/patrickweber/go/pkg/mod/github.com/containerssh/kubernetes@v0.9.8/config.go:73:6: unsupported type "float32"
/Users/patrickweber/go/pkg/mod/github.com/containerssh/security@v0.9.7/config.go:75:2: encountered struct field "Allow" without JSON tag in type "EnvConfig"
/Users/patrickweber/go/pkg/mod/github.com/containerssh/security@v0.9.7/config.go:78:2: encountered struct field "Deny" without JSON tag in type "EnvConfig"
/Users/patrickweber/go/pkg/mod/github.com/containerssh/security@v0.9.7/config.go:95:2: encountered struct field "Allow" without JSON tag in type "CommandConfig"
/Users/patrickweber/go/pkg/mod/github.com/containerssh/security@v0.9.7/config.go:126:2: encountered struct field "Allow" without JSON tag in type "SubsystemConfig"
/Users/patrickweber/go/pkg/mod/github.com/containerssh/security@v0.9.7/config.go:128:2: encountered struct field "Deny" without JSON tag in type "SubsystemConfig"
/Users/patrickweber/go/pkg/mod/github.com/containerssh/security@v0.9.7/config.go:158:2: encountered struct field "Allow" without JSON tag in type "SignalConfig"
/Users/patrickweber/go/pkg/mod/github.com/containerssh/security@v0.9.7/config.go:160:2: encountered struct field "Deny" without JSON tag in type "SignalConfig"`

I have exclude docker, this can not work with the operator-sdk because the docker dependency have no json tags(not you task and not relevant).
It is my first Kubernetes operator and I have only begin with implement the ContainerSSH.

**Comment by janoszen** [comment] 2021-03-13 11:42
@patsys thanks for this, this helps a lot. We'll fix these in the final release.

**Comment by janoszen** [comment] 2021-03-14 09:45
@patsys we have implemented checks for JSON tags in the config structure. However, I'm afraid you will have to mirror the Kubernetes config structure yourself since the QPS parameter is a float and the operator-sdk doesn't support that. You can copy the configuration structure and populate the fields as needed.

**Comment by patsys** [comment] 2021-03-14 15:23
@janoszen the json tags in the security module are all correct. The Kubernetes config I will try use a embedded struct when I try to implement this part and look then which type I use. Thanks for the fix.

**Comment by janoszen** [comment] 2021-03-14 15:24
Thanks, @patsys I will close this issue, feel free to reopen if you need additional help.

**Closed** 2021-03-14 15:37 UTC
Labels: feature
